# Shared farm layout and crop-maintenance settings.
#
# Coordinates use the game's southwest origin. Keep patches inside the active
# world and do not overlap them.


ENABLE_CACTUS_PATCH = True
ENABLE_PUMPKIN_PATCH = True
ENABLE_TREE_BUSH_STRIP = True
ENABLE_GRASS_STRIP = True
ENABLE_CARROT_FILL = True


ENABLE_WEIRD_SUBSTANCE_PRODUCTION = True
WEIRD_SUBSTANCE_TARGET = 1000
FERTILIZER_RESERVE = 0

FERTILIZE_PUMPKIN_HARVEST = True
FERTILIZE_CACTUS_HARVEST = False
FERTILIZE_REGULAR_HARVESTS = False


CACTUS_START_X = 0
CACTUS_START_Y = 17
CACTUS_SIZE = 15
CACTUS_WATER_THRESHOLD = 0.2


PUMPKIN_START_X = 15
PUMPKIN_START_Y = 0
PUMPKIN_SIZE = 17
PUMPKIN_WATER_THRESHOLD = 0.2


REGULAR_WATER_THRESHOLD = 0.15
